import React,{useEffect,useRef,useState} from 'react';
import ReactDOM from 'react-dom';
import {h} from './h.js';
import {downloadVerifiedBinary} from './lib.js';
import {readerIdentity,readerRuntime,readerPreferredMode,loadPdf,pdfTypes,readerWorker,pdfResources,makeRange} from './reader-tab.js';
const decode=value=>Uint8Array.from(atob(value),char=>char.charCodeAt(0));

function PdfPage({doc,number,width,zoom,root,onError}){
 const element=useRef(),canvas=useRef(),text=useRef();const [near,setNear]=useState(number===1),[size,setSize]=useState({width:595,height:842});
 useEffect(()=>{let alive=true;doc.getPage(number).then(page=>{if(alive){const v=page.getViewport({scale:1});setSize({width:v.width,height:v.height});}}).catch(onError);return()=>{alive=false;};},[doc,number]);
 useEffect(()=>{const observer=new IntersectionObserver(entries=>setNear(entries[0].isIntersecting),{root:root.current,rootMargin:'1000px 0px'});observer.observe(element.current);return()=>observer.disconnect();},[doc,number,root]);
 const scale=width/size.width*zoom,w=size.width*scale,height=size.height*scale;
 useEffect(()=>{if(!near)return;let stopped=false,paint,layer;void(async()=>{const page=await doc.getPage(number);if(stopped)return;const viewport=page.getViewport({scale}),ratio=Math.min(devicePixelRatio||1,2),c=canvas.current;
  c.width=Math.ceil(viewport.width*ratio);c.height=Math.ceil(viewport.height*ratio);c.style.width=viewport.width+'px';c.style.height=viewport.height+'px';
  const t=text.current;t.replaceChildren();t.style.width=viewport.width+'px';t.style.height=viewport.height+'px';t.style.setProperty('--scale-factor',viewport.scale);t.style.setProperty('--total-scale-factor',viewport.scale);t.style.setProperty('--scale-round-x','1px');t.style.setProperty('--scale-round-y','1px');
  paint=page.render({canvasContext:c.getContext('2d'),viewport,transform:[ratio,0,0,ratio,0,0]});await paint.promise;if(stopped)return;
  const {TextLayer}=pdfTypes();layer=new TextLayer({textContentSource:await page.getTextContent(),container:t,viewport});await layer.render();
 })().catch(error=>{if(!stopped&&error.name!=='RenderingCancelledException')onError(error);});return()=>{stopped=true;paint?.cancel();layer?.cancel();};},[doc,number,scale,near]);
 return h('div',{ref:element,className:'ib-pdf-page','data-pdf-page':number,style:{width:w,height}},near?h(React.Fragment,null,h('canvas',{ref:canvas,'aria-label':'PDF 第 '+number+' 页'}),h('div',{ref:text,className:'ib-reader-text-layer'})):h('span',{className:'ib-page-placeholder'},'第 '+number+' 页'));
}
function PdfFlow({doc,side,zoom,scrollRef,onScroll,onError,hand}){
 const [width,setWidth]=useState(500),drag=useRef();
 useEffect(()=>{const el=scrollRef.current,observer=new ResizeObserver(()=>setWidth(Math.max(100,el.clientWidth-24)));observer.observe(el);setWidth(Math.max(100,el.clientWidth-24));return()=>observer.disconnect();},[scrollRef]);
 return h('div',{ref:scrollRef,className:'ib-pdf-flow','data-pdf-side':side,'data-hand':hand||undefined,onScroll:event=>onScroll(side,event.currentTarget),
  onPointerDown:event=>{if(!hand||event.button!==0)return;event.preventDefault();drag.current={x:event.clientX,y:event.clientY,left:event.currentTarget.scrollLeft,top:event.currentTarget.scrollTop};event.currentTarget.setPointerCapture(event.pointerId);},
  onPointerMove:event=>{if(!drag.current)return;event.currentTarget.scrollLeft=drag.current.left+drag.current.x-event.clientX;event.currentTarget.scrollTop=drag.current.top+drag.current.y-event.clientY;},onPointerUp:()=>{drag.current=null;},onPointerCancel:()=>{drag.current=null;}},
  doc?Array.from({length:doc.numPages},(_,i)=>h(PdfPage,{key:i,doc,number:i+1,width,zoom,root:scrollRef,onError})):h('p',{className:'ib-reader-loading'},'正在读取 PDF…'));
}
function position(flow){const y=flow.scrollTop+8,pages=[...flow.querySelectorAll('[data-pdf-page]')],item=pages.find(p=>p.offsetTop+p.offsetHeight>y)??pages.at(-1);return item?{page:Number(item.dataset.pdfPage),fraction:Math.max(0,Math.min(1,(y-item.offsetTop)/item.offsetHeight))}:{page:1,fraction:0};}
function jump(flow,page,fraction=0){const item=flow?.querySelector(`[data-pdf-page="${page}"]`);if(item)flow.scrollTop=item.offsetTop+fraction*item.offsetHeight-8;}

export function ReaderBody({useTabInfo}){
 const {tab}=useTabInfo(),request=readerIdentity(tab?.contentId),key=tab?.contentId;
 const [state,setState]=useState({loading:true}),[doc,setDoc]=useState(null),[zhDoc,setZhDoc]=useState(null),[mode,setMode]=useState('original'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[refresh,setRefresh]=useState(0),[linked,setLinked]=useState(true),[stacked,setStacked]=useState(false),[hand,setHand]=useState(false),[zoom,setZoom]=useState({original:1,zh:1}),[pages,setPages]=useState({original:1,zh:1});
 const left=useRef(),right=useRef(),fullscreen=useRef(),syncing=useRef(null),openedZh=useRef(),extraDocs=useRef(new Set()),leases=useRef(new Set()),ownsFullscreen=useRef(false);
 const runtime=readerRuntime(),call=(method,args)=>runtime.call(method,{request:args}),onError=error=>setError(error.message??String(error));
 useEffect(()=>{const opened=event=>{if(event.detail.address===key)setRefresh(value=>value+1);};window.addEventListener('ibm-reader-open',opened);return()=>window.removeEventListener('ibm-reader-open',opened);},[key]);
 useEffect(()=>{let alive=true,task,port,range,opened;setState({loading:true});setDoc(null);setZhDoc(null);setMode('original');setError('');setPages({original:1,zh:1});setZoom({original:1,zh:1});openedZh.current=null;
  void(async()=>{await loadPdf();const {getDocument,PDFWorker,GlobalWorkerOptions}=pdfTypes(),workerUrl=readerWorker();GlobalWorkerOptions.workerSrc=workerUrl;opened=await call('tasks_reader_open',request);if(!alive){if(opened.lease)await call('tasks_reader_close',{...request,lease:opened.lease});return;}
   setState({...opened,sourceFormat:opened.format,archiveName:opened.fileName,loading:false});if(opened.translation?.status==='completed')setMode(readerPreferredMode(key));if(opened.format!=='pdf')return;
   port=new Worker(workerUrl,{type:'module'});range=makeRange(request,opened,runtime.call);range.onError=onError;task=getDocument({range,rangeChunkSize:262144,disableAutoFetch:true,disableStream:true,worker:new PDFWorker({port}),...pdfResources(call)});const pdf=await task.promise;if(alive)setDoc(pdf);else await pdf.destroy();
  })().catch(error=>{if(alive)setState({loading:false,error:error.message});});
  return()=>{alive=false;range?.abort();void task?.destroy();port?.terminate();for(const pdf of extraDocs.current)void pdf.destroy().catch(()=>{});extraDocs.current.clear();if(readerRuntime()){for(const lease of leases.current)void call('tasks_reader_close',{...request,lease}).catch(()=>{});leases.current.clear();if(opened?.lease)void call('tasks_reader_close',{...request,lease:opened.lease}).catch(()=>{});}if(ownsFullscreen.current&&document.fullscreenElement)void document.exitFullscreen().catch(()=>{});};
 },[key,refresh]);
 const translation=state.translation,tid=translation?.id;
 useEffect(()=>{if(!tid)return;let alive=true,timer;const poll=async()=>{try{const result=await call('tasks_translation_read',{...request,translationId:tid,limit:1});if(!alive)return;setState(old=>({...old,translation:result.translation}));if(result.translation.status==='completed')return;}catch{}if(alive)timer=setTimeout(poll,1500);};void poll();return()=>{alive=false;clearTimeout(timer);};},[key,tid]);
 useEffect(()=>{if(mode==='original'||zhDoc||translation?.status!=='completed')return;let alive=true,task,range,opened,loaded=false;setError('');setBusy(true);
  void(async()=>{opened=await call('tasks_reader_open',{...request,translationId:tid});if(!alive){await call('tasks_reader_close',{...request,lease:opened.lease});return;}leases.current.add(opened.lease);openedZh.current=opened;setState(old=>({...old,translation:opened.translation}));range=makeRange(request,opened,runtime.call);range.onError=onError;task=pdfTypes().getDocument({range,rangeChunkSize:262144,disableAutoFetch:true,disableStream:true,...pdfResources(call)});const pdf=await task.promise;if(alive){loaded=true;extraDocs.current.add(pdf);setZhDoc(pdf);}else await pdf.destroy();})().catch(error=>{if(alive)onError(error);}).finally(()=>{if(alive)setBusy(false);});
  return()=>{alive=false;if(!loaded){range?.abort();if(task)void task.destroy();}};
 },[key,tid,mode==='original',translation?.status]);
 const changeMode=next=>{setMode(next);if(ownsFullscreen.current&&document.fullscreenElement)void document.exitFullscreen().catch(()=>{});ownsFullscreen.current=false;};
 const exitDual=()=>changeMode('zh');
 useEffect(()=>{if(mode!=='dual')return;const keydown=event=>{if(event.key==='Escape')exitDual();};const exited=()=>{if(ownsFullscreen.current&&!document.fullscreenElement){ownsFullscreen.current=false;setMode('zh');}};window.addEventListener('keydown',keydown);document.addEventListener('fullscreenchange',exited);return()=>{window.removeEventListener('keydown',keydown);document.removeEventListener('fullscreenchange',exited);};},[mode]);
 const dual=()=>{setMode('dual');setTimeout(()=>{if(fullscreen.current?.requestFullscreen&&!document.fullscreenElement)void fullscreen.current.requestFullscreen().then(()=>{ownsFullscreen.current=true;}).catch(()=>{});},0);};
 const translate=async()=>{setBusy(true);let created;try{created=await call('tasks_translation_create',request);setState(old=>({...old,translation:created.translation}));if(created.translation.status==='completed')setMode('zh');else if(!created.reused)await runtime.translate(request,created.translation.id);else setError('任务正在进行，请查看翻译对话。');}catch(error){if(created&&!created.reused)await call('tasks_translation_cancel',{...request,translationId:created.translation.id}).catch(()=>{});onError(error);}finally{setBusy(false);}};
 const onScroll=(side,flow)=>{const p=position(flow);setPages(old=>old[side]===p.page?old:{...old,[side]:p.page});if(syncing.current===side)return;if(mode==='dual'&&linked){const other=side==='original'?'zh':'original';syncing.current=other;jump(other==='zh'?right.current:left.current,p.page,p.fraction);requestAnimationFrame(()=>{syncing.current=null;});}};
 const zoomTo=(side,value)=>setZoom(old=>linked?{original:value,zh:value}:{...old,[side]:value});
 const navigate=(side,number)=>{const d=side==='zh'?zhDoc:doc,n=Math.max(1,Math.min(d?.numPages??1,number||1));jump(side==='zh'?right.current:left.current,n);if(linked&&mode==='dual')jump(side==='zh'?left.current:right.current,n);};
 const save=async side=>downloadVerifiedBinary(side==='original'?`/api/lab-artifacts?kind=${request.kind}&bundleId=${encodeURIComponent(request.bundleId)}`:`/api/lab-artifacts?kind=translation&material=${request.kind}&projectId=${encodeURIComponent(request.projectId)}&bundleId=${encodeURIComponent(request.bundleId)}&translationId=${encodeURIComponent(tid)}`);
 const search=async()=>{const side=mode==='zh'?'zh':'original',pdf=side==='zh'?zhDoc:doc;if(!pdf||!query.trim())return;for(let i=0;i<pdf.numPages;i++){const n=(pages[side]+i-1)%pdf.numPages+1,content=await(await pdf.getPage(n)).getTextContent();if(content.items.map(x=>x.str??'').join(' ').toLowerCase().includes(query.toLowerCase())){navigate(side,n);return;}}setError('没有找到该文本');};
 const button=(label,onClick,disabled=false,active=false,title=label)=>h('button',{type:'button',className:'ib-act','data-active':active||undefined,onClick,disabled,title},label);
 const toolbar=side=>{const pdf=side==='zh'?zhDoc:doc;return h('div',{className:'ib-pdf-toolbar'},h('span',{className:'ib-pdf-language'},side==='zh'?'中文 PDF':'原文 PDF'),h('select',{'aria-label':side+' 缩放',value:zoom[side],onChange:event=>zoomTo(side,Number(event.target.value))},[.5,.75,1,1.25,1.5,2,3].map(n=>h('option',{key:n,value:n},n===1?'适合宽度':Math.round(n*100)+'%'))),button('⊖',()=>zoomTo(side,Math.max(.5,zoom[side]-.25))),button('⊕',()=>zoomTo(side,Math.min(3,zoom[side]+.25))),button('✋',()=>setHand(true),false,hand,'抓手拖动'),button('Ⅰ',()=>setHand(false),false,!hand,'选择文字'),button('↓',()=>void save(side).catch(onError),!pdf,false,'下载 '+(side==='zh'?'中文':'原文')+' PDF'),h('input',{'aria-label':side+' PDF 页码',type:'number',min:1,max:pdf?.numPages??1,value:pages[side],onChange:event=>navigate(side,Number(event.target.value))}),h('small',null,'/ '+(pdf?.numPages??'…')));};
 const pane=side=>h('section',{className:'ib-pdf-pane',key:side},toolbar(side),h(PdfFlow,{doc:side==='zh'?zhDoc:doc,side,zoom:zoom[side],scrollRef:side==='zh'?right:left,onScroll,onError,hand}),h('span',{className:'ib-pdf-page-indicator'},pages[side]+' / '+((side==='zh'?zhDoc:doc)?.numPages??'…')));
 if(state.loading)return h('div',{className:'ib-reader'},'正在读取已归档文献…');if(state.error)return h('div',{className:'ib-reader',role:'alert'},'无法打开文献：'+state.error);
 const content=h('div',{ref:mode==='dual'?fullscreen:undefined,className:'ib-reader'+(mode==='dual'?' ib-reader-fullscreen':''),'data-reader-mode':mode},h('header',{className:'ib-reader-header'},h('span',{title:state.title},state.title),mode==='dual'?button('退出全屏',exitDual):null),
  h('nav',{className:'ib-reader-controls'},button('原文',()=>changeMode('original'),false,mode==='original'),button('中文',()=>changeMode('zh'),translation?.status!=='completed',mode==='zh'),button('双语对照',dual,translation?.status!=='completed',mode==='dual'),button(translation?.status==='completed'?'阅读译文':['queued','running'].includes(translation?.status)?'翻译中…':'翻译',translate,busy||state.sourceFormat!=='pdf'||['queued','running'].includes(translation?.status)),['queued','running'].includes(translation?.status)?button('取消翻译',async()=>{try{const result=await call('tasks_translation_cancel',{...request,translationId:tid});setState(old=>({...old,translation:result.translation}));}catch(error){onError(error);}}):null,mode==='dual'?h(React.Fragment,null,h('label',null,h('input',{type:'checkbox',checked:linked,onChange:e=>setLinked(e.target.checked)}),'双屏关联'),h('label',null,h('input',{type:'checkbox',checked:stacked,onChange:e=>setStacked(e.target.checked)}),'上下视图')):null,h('input',{'aria-label':'查找 PDF 文本',placeholder:'查找文本',value:query,onChange:e=>setQuery(e.target.value),onKeyDown:e=>{if(e.key==='Enter')void search().catch(onError);}}),button('查找',()=>void search().catch(onError),!doc)),
  error?h('div',{className:'ib-reader-error',role:'alert'},error):null,translation&&translation.status!=='completed'?h('small',{className:'ib-reader-status'},translation.stage+(translation.totalBlocks?` · ${translation.completedBlocks??0}/${translation.totalBlocks} 段`:'')+(translation.error?' · '+translation.error:'')):null,(translation?.pdfWarnings??[]).length?h('small',{className:'ib-reader-status'},translation.pdfWarnings.join('；')):null,
  state.format==='pdf'?h('div',{className:'ib-pdf-panes','data-stacked':stacked&&mode==='dual'||undefined},mode==='dual'?h(React.Fragment,null,pane('original'),pane('zh')):pane(mode==='zh'?'zh':'original')):null,
  state.format==='zip'?h('div',{className:'ib-reader-files'},button('保存 SI',()=>void save('original').catch(onError)),h('p',null,'SI 文件列表'),(state.entries??[]).map(entry=>h('div',{key:entry.index},entry.name,' · '+Math.round(entry.bytes/1024)+' KB',entry.pdf?button('阅读 PDF',async()=>{try{const file=await call('tasks_reader_zip_pdf',{...request,index:entry.index}),pdf=await pdfTypes().getDocument({data:decode(file.base64),...pdfResources(call)}).promise;extraDocs.current.add(pdf);setDoc(pdf);setState(old=>({...old,format:'pdf',fileName:file.name}));}catch(error){onError(error);}}):null))):null,
  state.sourceFormat==='zip'&&state.format==='pdf'?button('返回 SI 文件列表',()=>{setDoc(null);void doc?.destroy().catch(()=>{});extraDocs.current.delete(doc);setState(old=>({...old,format:'zip'}));}):null,state.format==='unsupported'?h('p',null,'此格式请保存后使用对应软件打开。',button('保存材料',()=>void save('original').catch(onError))):null);
 return mode==='dual'?h(React.Fragment,null,h('div',{className:'ib-reader'},'双语 PDF 已全屏打开',button('返回侧栏',exitDual)),ReactDOM.createPortal(content,document.body)):content;
}
export const readerStyles=`
.ib-reader{font-family:system-ui,Segoe UI,Microsoft YaHei,sans-serif;font-size:12px;display:flex;flex-direction:column;height:100%;min-height:0;background:#fff;color:#303744;overflow:hidden}
.ib-reader-fullscreen{position:fixed;inset:0;z-index:2147483000;width:100vw;height:100vh}
.ib-reader-header{display:flex;align-items:center;justify-content:space-between;padding:6px 10px;border-bottom:1px solid #e1e5eb;gap:8px;min-height:30px;box-sizing:border-box}.ib-reader-header>span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-weight:600}
.ib-reader-controls,.ib-pdf-toolbar{display:flex;gap:5px;align-items:center;flex-wrap:wrap;padding:4px 6px;border-bottom:1px solid #e1e5eb;flex:none;background:#fff;min-height:30px;box-sizing:border-box}
.ib-reader-controls label{display:flex;align-items:center;gap:3px;white-space:nowrap}.ib-reader .ib-act{font:inherit;border:1px solid transparent;border-radius:3px;background:transparent;color:inherit;padding:3px 7px;cursor:pointer;white-space:nowrap}.ib-reader .ib-act:hover{background:#eef1f5}.ib-reader .ib-act[data-active=true]{background:#dde5ee;color:#21455e}.ib-reader button:disabled{opacity:.4;cursor:default}
.ib-reader input,.ib-reader select{font:inherit;background:#fff;color:inherit;border:1px solid #dce1e8;border-radius:3px;padding:3px;min-width:0}.ib-reader input[type=number]{width:42px}.ib-reader input[aria-label="查找 PDF 文本"]{width:85px}.ib-pdf-toolbar select{width:85px}.ib-pdf-language{font-weight:500;color:#6a7380;white-space:nowrap}.ib-pdf-toolbar small{white-space:nowrap}
.ib-pdf-panes{display:flex;flex:1;min-height:0;min-width:0}.ib-pdf-panes[data-stacked=true]{flex-direction:column}.ib-pdf-pane{position:relative;display:flex;flex-direction:column;min-width:0;min-height:0;flex:1;border-right:1px solid #dce1e8}.ib-pdf-flow{position:relative;overflow:auto;flex:1;min-height:0;background:#f0f2f5;overscroll-behavior:contain;scrollbar-gutter:stable;padding:12px;box-sizing:border-box;overflow-anchor:none}.ib-pdf-flow[data-hand=true]{cursor:grab;user-select:none}.ib-pdf-flow[data-hand=true]:active{cursor:grabbing}.ib-pdf-flow[data-hand=true] .ib-reader-text-layer{pointer-events:none}
.ib-pdf-page{position:relative;background:#fff;box-shadow:0 0 0 1px #e0e3e7,0 2px 5px #0000000b;margin:0 auto 14px;flex:none}.ib-pdf-page canvas{display:block}.ib-page-placeholder{color:#a0a8b3;position:absolute;top:40%;left:42%}.ib-pdf-page-indicator{position:absolute;bottom:10px;left:50%;transform:translateX(-50%);padding:4px 12px;border-radius:4px;background:#56616bd9;color:white;pointer-events:none}.ib-reader-status,.ib-reader-error{padding:5px 10px}.ib-reader-error{color:#af3333;background:#fff0ee}.ib-reader-files{overflow:auto;padding:10px}.ib-reader-loading{padding:30px;text-align:center}
.ib-reader-text-layer{position:absolute;inset:0;overflow:clip;line-height:1;text-align:initial;text-size-adjust:none;forced-color-adjust:none}.ib-reader-text-layer :is(span,br){color:transparent;position:absolute;white-space:pre;cursor:text;transform-origin:0% 0%;font-size:calc(var(--total-scale-factor) * var(--font-height));transform:rotate(var(--rotate,0deg)) scaleX(var(--scale-x,1))}.ib-reader-text-layer ::selection{background:rgba(60,130,220,.3)}
`;
